```{r lib}
library(ggplot2)
library(dplyr)
library(ggplot2)
library(reshape2)
```

```{r global_settings}
mendelian_colors <- c("Identical" = "#56B4E9", "Paternal" = "#7bda7c", "Maternal"= '#0072B2', "Violation"= '#D55E00')
precision_recall_colors <- c("Precision" = "#56B4E9", "Recall" = "#7bda7c")
```


# Mendelian violation analysis using trios

HG002, HG005: gAIRR-call

HG00514, HG00733, NA19240: gAIRR-annotate


```{r check_mendelian_violation}
df.trio.all <- read.delim("Trio_result.tsv", header=T)

df.trio.all.melt <- melt(df.trio.all)

for (ch in c("TRV", "TRJ", "IGV")) {
# for (ch in c("TRV", "TRJ", "IGV", "IGJ")) {
  for (nov in c("Known", "Novel")) {
    title <- paste(ch, nov)
    fig <- ggplot(df.trio.all.melt %>% filter((Novelty == nov) & (Chain == ch)), aes(fill=variable, y=value, x=Sample)) +
      geom_bar(position="stack", stat="identity") +
      ggtitle(title)+
      labs(x = "Sample", y = "Count", fill = "") +
      scale_fill_manual(values = mendelian_colors) + 
      theme_bw() +
      theme(legend.position = "bottom")
    title <- paste(ch, nov, sep="_")
    fn <- paste("figures/", title, ".pdf", sep="")
    ggsave(fn, fig, width=5, height=4)
  }
}

# ggplot(df.trio.all.melt %>% filter((Novelty == "novel") & (Chain %in% c("TRV", "TRJ"))), aes(fill=variable, y=value, x=Sample)) +
#   geom_bar(position="stack", stat="identity") +
#   ggtitle("TR")+
#   labs(x = "Sample", y = "Count", fill = "") +
#   scale_fill_manual(values = mendelian_colors) + 
#   theme_bw() +
#   theme(legend.position = "bottom")
# ggsave("figures/TR.pdf", width=5, height=4)
# 
# ggplot(df.trio.all.melt %>% filter((Novelty == "novel") & (Chain %in% c("TRV", "TRJ"))), aes(fill=variable, y=value, x=Sample)) +
#   geom_bar(position="stack", stat="identity") +
#   ggtitle("TR novel")+
#   labs(x = "Sample", y = "Count", fill = "") +
#   scale_fill_manual(values = mendelian_colors) + 
#   theme_bw() +
#   theme(legend.position = "bottom")
# ggsave("figures/TR_novel.pdf", width=5, height=4)
# 
# ggplot(df.trio.all.melt %>% filter((Novelty == "known") & (Chain %in% c("TRV", "TRJ"))), aes(fill=variable, y=value, x=Sample)) +
#   geom_bar(position="stack", stat="identity") +
#   ggtitle("TR known")+
#   labs(x = "Sample", y = "Count", fill = "") +
#   scale_fill_manual(values = mendelian_colors) + 
#   theme_bw() +
#   theme(legend.position = "bottom")
# ggsave("figures/TR_known.pdf", width=5, height=4)
# 
# ggplot(df.trio.all.melt %>% filter((Novelty == "novel") & (Chain %in% c("IGV", "IGJ"))), aes(fill=variable, y=value, x=Sample)) +
#   geom_bar(position="stack", stat="identity") +
#   ggtitle("IG novel")+
#   labs(x = "Sample", y = "Count", fill = "") +
#   scale_fill_manual(values = mendelian_colors) + 
#   theme_bw() +
#   theme(legend.position = "bottom")
# ggsave("figures/IG_novel.pdf", width=5, height=4)
# 
# ggplot(df.trio.all.melt %>% filter((Novelty == "known") & (Chain %in% c("IGV", "IGJ"))), aes(fill=variable, y=value, x=Sample)) +
#   geom_bar(position="stack", stat="identity") +
#   ggtitle("IG known")+
#   labs(x = "Sample", y = "Count", fill = "") +
#   scale_fill_manual(values = mendelian_colors) + 
#   theme_bw() +
#   theme(legend.position = "bottom")
# ggsave("figures/IG_known.pdf", width=5, height=4)

```

```{r check_mendelian_violation_tr_ig}
ggplot(df.trio.all.melt %>% filter(Chain %in% c("TRV", "TRJ")), aes(fill=variable, y=value, x=Sample)) +
  geom_bar(position="stack", stat="identity") +
  facet_grid(.~Novelty) +
  # ggtitle("TR") +
  labs(x = "Sample", y = "Count", fill = "") +
  scale_fill_manual(values = mendelian_colors) + 
  theme_bw() +
  theme(legend.position = "none", strip.background = element_rect(color="white", fill="white", size=0.5, linetype="solid"), strip.text = element_text(face="bold"))
ggsave("figures/TR.pdf", width=9, height=3)

# ggplot(df.trio.all.melt %>% filter(Chain %in% c("IGV", "IGJ")), aes(fill=variable, y=value, x=Sample)) +
ggplot(df.trio.all.melt %>% filter(Chain %in% c("IGV")), aes(fill=variable, y=value, x=Sample)) +
  geom_bar(position="stack", stat="identity") +
  facet_grid(.~Novelty) +
  # ggtitle("IG") +
  labs(x = "Sample", y = "Count", fill = "") +
  scale_fill_manual(values = mendelian_colors) + 
  theme_bw() +
  theme(legend.position = "none", strip.background = element_rect(color="white", fill="white", size=0.5, linetype="solid"), strip.text = element_text(face="bold"))
ggsave("figures/IG.pdf", width=9, height=3)

```

```{r violation_rate}
df.trio.all %>% filter(Chain %in% "IGV") %>% group_by(Novelty) %>% summarise(Violation.Rate = sum(Violation) / sum(Violation+Paternal+Maternal+Identical))
# df.trio.all %>% filter(Chain %in% "TRV") %>% group_by(Novelty) %>% summarise(Violation.Rate = sum(Violation) / sum(Violation+Paternal+Maternal+Identical))
```

# gAIRR-call accuracy

```{r call_accuracy}
df.gairr.call <- melt(read.delim("HG001_accuracy.tsv", header=T) %>% filter(Chain %in% c("TRV", "TRJ", "IGHV", "IGKV", "IGLV")))

df.gairr.call$Chain <- factor(df.gairr.call$Chain, levels=c("TRV", "TRJ", "IGHV", "IGKV", "IGLV"))
# df.gairr.call$Chain <- factor(df.gairr.call$Chain, levels=c("TRV", "TRJ", "IGHV", "IGKV", "IGLV", "IGJ"))

ggplot(df.gairr.call, aes(fill=variable, y=value, x=Chain)) +
  geom_bar(position="dodge", stat="identity") +
  ggtitle("")+
  labs(x = "Chain", y = "", fill = "") +
  scale_fill_manual(values = precision_recall_colors) +
  theme_bw() +
  theme(legend.position = "none")
ggsave("figures/HG001-gairr_call.pdf", width=10, height=4)
```

