---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
```

```{r trbv}
df_trbv <- read.delim("../data/trbv_top150.labelled.txt", header = F, sep = "\t")
df_trbv$rank <- c(1: nrow(df_trbv))

cols <- c("0" = "#E69F00", "1" = "#56B4E9")
ggplot(df_trbv, aes(x=rank, y=V2)) + 
  geom_bar(aes(fill = factor(V3)), stat = "identity") + geom_line() +
  labs(x = "Rank", y = "Score", fill = "", title = "Top-150 calls by BLASTn, TRBV") +
  theme_bw() +
  # theme(legend.position = "bottom") +
  theme(legend.position = c(0.8, 0.8)) +
  scale_fill_manual(
    values = cols,
    breaks = c("0", "1"),
    labels = c("Unannotated", "Annotated")
  )
```

```{r trav}
df_trav <- read.delim("../data/trav_top150.labelled.txt", header = F, sep = "\t")
df_trav$rank <- c(1: nrow(df_trav))

cols <- c("0" = "#E69F00", "1" = "#56B4E9")
ggplot(df_trav, aes(x=rank, y=V2)) + 
  geom_bar(aes(fill = factor(V3)), stat = "identity") + geom_line() +
  labs(x = "Rank", y = "Score", fill = "", title = "Top-150 calls by BLASTn, TRAV") +
  theme_bw() +
  # theme(legend.position = "bottom") +
  theme(legend.position = c(0.8, 0.8)) +
  scale_fill_manual(
    values = cols,
    breaks = c("0", "1"),
    labels = c("Unannotated", "Annotated")
  )
```